import Foundation

/// App-wide constants for ClipVault
enum Constants {

    // MARK: - App Info

    /// Bundle identifier for the app
    static let bundleIdentifier = "com.edaboard.app"

    /// App name for display
    static let appName = "EdaBoard"

    // MARK: - History Settings

    /// Default history limit
    static let defaultHistoryLimit = 100

    /// Minimum allowed history limit
    static let minHistoryLimit = 10

    /// Maximum allowed history limit
    static let maxHistoryLimit = 1000

    // MARK: - Polling Settings

    /// Default clipboard polling interval in seconds
    static let defaultPollingInterval: TimeInterval = 0.5

    /// Timer tolerance for power efficiency
    static let pollingTolerance: TimeInterval = 0.1

    // MARK: - Content Limits

    /// Maximum text content size in bytes (1 MB)
    static let maxTextSize = 1 * 1024 * 1024

    /// Maximum image size in bytes (10 MB)
    static let maxImageSize = 10 * 1024 * 1024

    // MARK: - Image Processing

    /// Maximum thumbnail dimension (width or height)
    static let thumbnailMaxSize: CGFloat = 200

    /// JPEG compression quality for thumbnails
    static let thumbnailQuality: CGFloat = 0.7

    // MARK: - Duplicate Detection

    /// Time window for duplicate detection in seconds
    static let duplicateDetectionWindow: TimeInterval = 2.0

    // MARK: - UI Dimensions

    /// Default popover width
    static let popoverWidth: CGFloat = 320

    /// Default popover height
    static let popoverHeight: CGFloat = 400

    /// Maximum preview text length
    static let previewTextLength = 100

    // MARK: - Hotkey Defaults

    /// Default hotkey key code (V key)
    static let defaultHotkeyKeyCode: UInt32 = 9

    /// Default hotkey modifiers (Cmd + Shift)
    static let defaultHotkeyModifiers: UInt32 = 0x100108

    // MARK: - Sensitive Content Types

    /// Pasteboard types that indicate sensitive content (should be filtered)
    static let sensitiveTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "org.nspasteboard.TransientType"
    ]

    // MARK: - Performance Budgets

    /// Target time for hotkey to UI visible (milliseconds)
    static let hotkeyToUIBudgetMs = 100

    /// Target time for search filtering (milliseconds)
    static let searchBudgetMs = 50

    /// Target idle CPU usage (percentage)
    static let idleCPUBudget = 0.1

    /// Target idle memory (MB)
    static let idleMemoryBudgetMB = 30

    /// Target memory with 100 text items (MB)
    static let activeTextMemoryBudgetMB = 50

    /// Target memory with mixed content (MB)
    static let activeMixedMemoryBudgetMB = 200

    // MARK: - UserDefaults Keys

    enum UserDefaultsKeys {
        static let historyLimit = "historyLimit"
        static let globalHotkeyKeyCode = "globalHotkeyKeyCode"
        static let globalHotkeyModifiers = "globalHotkeyModifiers"
        static let startAtLogin = "startAtLogin"
        static let soundEffectsEnabled = "soundEffectsEnabled"
        static let pollingInterval = "pollingInterval"
        static let ignoredAppBundleIds = "ignoredAppBundleIds"
        static let filterSensitiveContent = "filterSensitiveContent"
        static let hasCompletedOnboarding = "hasCompletedOnboarding"
        static let lastLaunchVersion = "lastLaunchVersion"
    }
}
